import React from "react";
import Header from "../Common/Header";
import Footer from "../Common/Footer";
import bgImage from "../../public/revamp/bg-new.png";

const AboutMain = () => {
  return (
    <>
      <div
        style={{
          backgroundImage: `url(${bgImage.src})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
        }}
        className="w-full h-full"
      >
        <div className="w-full">
          <Header type="dark" />
        </div>
        <div className="w-full lg:p-10 lg:pb-0 mt-10 p-5 pb-0 flex justify-center items-center flex-col">
          <h1
            style={{
              background:
                "linear-gradient(99deg, #FFF 49.91%, rgba(255, 255, 255, 0.00) 112.45%)",
              backgroundClip: "text",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
            className="w-full text-center text-5xl lg:text-7xl font-bold"
          >
            GDPR
          </h1>
          <p
            style={{
              color: "rgba(255, 255, 255, 0.80)",
            }}
            className="w-full text-center mt-4"
          >
            Last updated: 14 March 2024
          </p>
          <p
            style={{
              color: "rgba(255, 255, 255, 0.80)",
            }}
            className="w-full p-5 mt-5 text-center lg:text-start text-xl"
          >
            Welcome to Noww, Inc., dba Circle.ooo. Noww, Inc. (“us”, “we”, or
            “our”) operates https://noww.co and https://www.circle.ooo mobile
            application (hereinafter referred to as “Service”). Our Privacy
            Policy governs your visit to https://noww.co or
            https://www.circle.ooo and our web and mobile applications, and
            explains how we collect, safeguard and disclose information that
            results from your use of our Service. We use your data to provide
            and improve Service. By using Service, you agree to the collection
            and use of information in accordance with this policy. Unless
            otherwise defined in this Privacy Policy, the terms used in this
            Privacy Policy have the same meanings as in our Terms and
            Conditions. Our Terms and Conditions (“Terms”) govern all use of our
            Service and together with the Privacy Policy constitutes your
            agreement with us (“agreement”).
          </p>
          <p
            style={{
              color: "rgba(255, 255, 255, 0.80)",
            }}
            className="w-full p-5 text-center lg:text-start text-xl"
          >
            Definitions: means the https://noww.co website
            https://www.circle.ooo means progressive web and mobile applications
            operated by Noww, Inc.
          </p>
          <p
            style={{
              color: "rgba(255, 255, 255, 0.80)",
            }}
            className="w-full p-5 text-center lg:text-start text-xl"
          >
            PERSONAL DATA means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
        </div>
      </div>
      <div className="w-full bg-[#070317] lg:p-10 lg:pt-0 pt-0 p-5 flex justify-center items-center flex-col">
        <p
          style={{
            color: "rgba(255, 255, 255, 0.80)",
          }}
          className="w-full p-5 text-center lg:text-start text-xl"
        >
          USAGE DATA is data collected automatically either generated by the use
          of Service or from Service infrastructure itself (for example, the
          duration of a page visit). are small files stored on your device
          (computer or mobile device).
        </p>
      </div>
      <div className="w-full h-fll">
        <Footer />
      </div>
    </>
  );
};

export default AboutMain;
